apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-deployment
spec:
  selector:
    matchLabels:
      app: command
  template:
    metadata:
      labels:
        app: command
    spec:
      containers:
      - name: command
        image: container-registry.docker.local:5000/command.service:0.0.6
        env:          
          - name: SqlDbSettings__Server
            value: mssql-clusterip-service
          - name: SqlDbSettings__Port
            value: "1433"
          - name: SqlDbSettings__DbName
            value: commandsdb
          - name: SqlDbSettings__User
            value: sa
          - name: SqlDbSettings__Password
            valueFrom:
              secretKeyRef:
                name: mssql
                key: SA_PASSWORD
          - name: RabbitMqSettings__Host
            value: rabbitmq-clusterip-service
          - name: PlatformGrpcUrl
            value: http://platform-cluster-ip-service:666
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 5265
